version: "3.2"
services:
    db:
        image: postgres:11
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=commoodity
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data
    localstack:
        image: localstack/localstack:latest
        container_name: localstack
        ports:
            - "4572:4572"
            - "4575:4575"
            - "8055:8080"
        environment:
            - SERVICES=s3,sns
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - "./.localstack:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    database_data:
